name: Run JavaScript Function

on:
  push:
    branches:
      - main

jobs:
  run_function:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run JavaScript function
      run: |
        node server/db-to-json.js
