name: Process Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_function:
    runs-on: ubuntu-latest
    environment: 'shafi-main-runner'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run Data Processor
      run: |
        node server/db-to-json.js
      env:
        SB_URL: ${{ secrets.SB_URL }}
        SB_API_PASS: ${{ secrets.SB_API_PASS }}
